version: "2.1"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022 #optional
      - PLEX_CLAIM= #optional
      - device=/dev/dri:/dev/dri
    volumes:
      - ./:/config
      - /mnt/dietpi_userdata/files/tvseries:/tv
      - /mnt/dietpi_userdata/files/movies:/movies
      - /mnt/dietpi_userdata/files/music:/music
    restart: unless-stopped
