version: '3.3'
services:
    filebrowser:
        container_name: filebrowser
        env_file: .env
        volumes:
            - '/mnt/dietpi_userdata/files/:/srv'
            - './filebrowser.db:/database.db'
            - './.filebrowser.json:/.filebrowser.json'
        ports:
            - '8090:80'
        image: filebrowser/filebrowser
        restart: unless-stopped
networks:
  default:
    external:
      name: $DOCKER_MY_NETWORK







